export const coins = [
  {
    Id: "1182",
    Url: "https://www.cryptocompare.com/coins/btc/overview",
    ImageUrl: "https://www.cryptocompare.com/media/19633/btc.png",
    Name: "BTC",
    Symbol: "BTC",
    CoinName: "Bitcoin",
    FullName: "Bitcoin (BTC)",
    Algorithm: "SHA256",
    ProofType: "PoW",
    TotalCoinSupply: "21000000",
},
{
    Id: "7605",
    Url: "https://www.cryptocompare.com/coins/eth/overview",
    ImageUrl: "https://www.cryptocompare.com/media/20646/eth_logo.png",
    Name: "ETH",
    Symbol: "ETH",
    CoinName: "Ethereum",
    FullName: "Ethereum (ETH)",
    Algorithm: "Ethash",
    ProofType: "PoW",
    TotalCoinSupply: "0",
},
{
    Id: "3808",
    Url: "https://www.cryptocompare.com/coins/ltc/overview",
    ImageUrl: "https://www.cryptocompare.com/media/19782/litecoin-logo.png",
    Name: "LTC",
    Symbol: "LTC",
    CoinName: "Litecoin",
    FullName: "Litecoin (LTC)",
    Algorithm: "Scrypt",
    ProofType: "PoW",
    TotalCoinSupply: "84000000",
},
];
